### ISSUE TITLE
Compatibility of ignite with torchtext

### ISSUE THREAD

**Issue by johncai117** [Sudy/coling2018#2]
There seems to be an error due to the use of torch text with ignite. Is there an easy fix for this?

> 
> 2019-12-02 20:20:34,847 - INFO - main.py --gpu 0 --model TE --resume model/TE_avg_16_100_100_0.0005_0.1_epoch_10_17974_model_136_microf1=0.641.pth
> 2019-12-02 20:20:55,144 - INFO - ====> loading model from model/TE_avg_16_100_100_0.0005_0.1_epoch_10_17974_model_136_microf1=0.641.pth
> 2019-12-02 20:20:55,241 - INFO - Engine run starting with max_epochs=1.
> 2019-12-02 20:20:55,269 - ERROR - Current run is terminating due to exception: input must contain <class 'torch.Tensor'>, dicts or lists; found <class 'NoneType'>.
> 2019-12-02 20:20:55,269 - ERROR - Engine run is terminating due to exception: input must contain <class 'torch.Tensor'>, dicts or lists; found <class 'NoneType'>.
> Traceback (most recent call last):
>   File "main.py", line 222, in <module>
>     run(args)
>   File "main.py", line 161, in run
>     run_test(model, testor, test_loader, args.resume, logger)
>   File "main.py", line 133, in run_test
>     _, microf1, test_auc = evaluate(evaler, loader)
>   File "main.py", line 121, in evaluate
>     engine.run(loader)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 446, in run
>     self._handle_exception(e)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
>     raise e
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 433, in run
>     hours, mins, secs = self._run_once_on_dataset()
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
>     self._handle_exception(e)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
>     raise e
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 391, in _run_once_on_dataset
>     self.state.output = self._process_function(self, batch)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/__init__.py", line 92, in _inference
>     x, y = prepare_batch(batch, device=device, non_blocking=non_blocking)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/engine/__init__.py", line 13, in _prepare_batch
>     convert_tensor(y, device=device, non_blocking=non_blocking))
>   File "/usr/local/lib/python3.6/dist-packages/ignite/utils.py", line 19, in convert_tensor
>     return apply_to_tensor(input_, _func)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/utils.py", line 25, in apply_to_tensor
>     return apply_to_type(input_, torch.Tensor, func)
>   File "/usr/local/lib/python3.6/dist-packages/ignite/utils.py", line 41, in apply_to_type
>     .format(input_type, type(input_))))
> TypeError: input must contain <class 'torch.Tensor'>, dicts or lists; found <class 'NoneType'>

**Comment by Sudy** [comment]
Please use the ignite with this repo instead of the one installed in your computer, because I have made some changes to the ignite codes.
